### ISSUE TITLE
Ellipsoid scaling

### ISSUE THREAD

**Issue by nensanders** [sebh/UnrealEngineSkyAtmosphere#9]
Hi Sébastien,
thank you for sharing this awesome technique. I could already implement the approach in a toy project vr space flight simulator.  https://www.youtube.com/watch?v=LGN-KqRX9Z4
Since the simulation is rather realistic I have a non-spherical earth.
Where would be the best place to skew the calculations so that the horizon (EarthBottomRadius) starts 21km lower on the north/south pole? 
I assume replacing all ray to sphere intersection calculations might be too costly for a non-spherical on the Oculus Quest.
Thanks in advance.

**Comment by Angelo1211** [comment]
Hmm, interesting problem. Don't have much to add myself except that this will probably complicate beyond the intersection calcs as the LUT parametrizations also assume the planet is spherical.

**Comment by sebh** [comment]
Hi,
Great to know that you implemented it successfully!

Indeed that is an interesting problem (not the first time I see that request)
Some things to do to fix the algorithm form the top of my head:
- the skyview lut parameterisation should be changed to handle the non spherical earth
- tracing up to earth ground and for shadowing should intersect with an ellispoid

Or because deformation is not that big for the size of the atmosphere over the planet, you could continue to do all light simulation in sphere space and assume it would look the same on ellipsoid. Then simply transform from ellipsoid to sphere space (rotate/scale linear transform) before doing any LUT sampling. Would be an approximation but a likely a good one.

**Comment by nensanders** [comment]
Thanks, I think I will go with the approximation.
Also some more improvements: https://youtu.be/pKQA8lMvjwU
